### ISSUE TITLE
warning: UIManager['YoutubeView'] is no longer supported. Use UIManager.getViewManagerConfig('YoutubeView') instead

### ISSUE THREAD

**Issue by ParthChugh** [up-inside/react-native-youtube-sdk#13]
React Native version: 0.60.3
React : 16.8.6

**Comment by farad4y** [comment]
It is just warnings, when time is up, we can upgrade or If you have time, push a commit

**Comment by Cyberfolks** [comment]
im facing same issue on react-native: 59.10
