### ISSUE TITLE
IOS FullScreenButton issue

### ISSUE THREAD

**Issue by sikeeoh** [up-inside/react-native-youtube-sdk#14]
```
var playerVars:[String: Any] = [
        "controls" : "0",
        "showinfo" : "0", 
        "autoplay": "0",
        "rel": "0",
        "modestbranding": "1",
        "iv_load_policy" : "3",
        "fs": "0",
        "ecver" : "2",
        "playsinline" : "1"
    ]
```

![image](https://user-images.githubusercontent.com/28793321/62823831-b5d90080-bbd0-11e9-9306-ba487d91fe5f.png)
![image](https://user-images.githubusercontent.com/28793321/62823804-54b12d00-bbd0-11e9-8a71-fad0117e98e4.png)

The full screen button is hidden by the title and thumbnail.

But
Setting "showinfo" to an empty value causes the button to appear on the playbar.
Please fix the issue in the next version.
![image](https://user-images.githubusercontent.com/28793321/62823812-73172880-bbd0-11e9-8e48-08c6865ddd9b.png)

**Comment by farad4y** [comment]
Okay
