### ISSUE TITLE
iOS: Audio plays only on headphones or bluetooth, loud speaker are silent

### ISSUE THREAD

**Issue by grafosecondo** [up-inside/react-native-youtube-sdk#16]
On iOS 12.1, React 0.59.3, evertything works fine but audio on phone speakers. To hear the video sound track I need to connect some kind of headphones.

Is there something I am missing? Thanks

**Comment by farad4y** [comment]
If you try on real device, you need to turn slient switch on.

**Comment by farad4y** [comment]
https://images.app.goo.gl/oqrLctVuis9DdKQA8 @grafosecondo
