### ISSUE TITLE
Installing on android (MainActivity.kt)

### ISSUE THREAD

**Issue by jbburf** [up-inside/react-native-youtube-sdk#18]
Hi @srfaytkn,

I ran through your setup and have it working in iOS but the android setup doesn't seem to work. Current versions of react-native (I'm using 0.60.5) create a MainActivity.kt file instead of a MainApplication.java, how would I link this in Kotlin versus your instructions in Java? Thanks in advance!

Ben

**Comment by farad4y** [comment]
@srfaytkn

**Comment by jbburf** [comment]
Hi @srfaytkn, I've searched for a solution but I'm still not finding a way to make this work. Can you please comment and update the readme for the kotlin install steps?

**Comment by farad4y** [comment]
I think @srfaytkn don’t have enough time for this.

**Comment by jbburf** [comment]
@srfaytkn ping! Can you at least respond?

@farad4y thanks for trying to direct this to the right person :)

**Comment by farad4y** [comment]
@srfaytkn Olum su adama bir cevap yaz, aci cekiyor belli ki.

**Comment by srfaytkn** [comment]
@jbburf MainApplication.kt should be like this 
`class MainApplication : NavigationApplication() {
    protected val packages: List<ReactPackage>
        get() {
            val packages = PackageList(this).packages
            packages.add(RNSpotifyPackage())
            packages.add(YouTubeSdkPackage())
            return packages
        }
     ...
}
`
