### ISSUE TITLE
Not working after screen changing

### ISSUE THREAD

**Issue by marksturm** [up-inside/react-native-youtube-sdk#19]
Heya - very good work. But if i change the the screen and go back, or come from another screen, then the video does not load.

**Comment by farad4y** [comment]
It is hard to answer that because it depends on which navigation library you use. 
you can do this with React Native Navigation(overlay) or React Navigation. 

I can’t share source code but it is possible. Check it out [Charmy App](https://charmy.app)

**Comment by marksturm** [comment]
Oh sorry, i used React-Navigation (https://reactnavigation.org/)... would be really nice to give me a a hint :)

**Comment by marksturm** [comment]
Ok, here is the hint for everyone ... if you use react-navigation and the  drawer, you need to rerender the youtube view...

componentDidMount() {
```
const { navigation } = this.props;
  // Add the event listener
  this.focusListener = navigation.addListener('willFocus', () => {
    this.setState({ key: Math.random() });
  });
}

componentWillUnmount() {
  // Remove the event listener
  this.focusListener.remove();
}
```

`<YouTubePlayer
      key={this.state.key} //<<-- This is the importent KEY!! ;-)
      ref={ref => (this.youTubePlayer = ref)}
      videoId="t_aIEOqB8VM"
      autoPlay={false}
      fullscreen={false}
      showFullScreenButton={true}
      showSeekBar={true}
      showPlayPauseButton={true}
      startTime={5}
      style={{ width: "100%", height: 200 }}
      onError={e => console.log(e)}
      onChangeState={e => console.log(e)}
      onChangeFullscreen={e => console.log(e)}
/>`
