### ISSUE TITLE
on build got 195 error on ios 

### ISSUE THREAD

**Issue by imadarif** [up-inside/react-native-youtube-sdk#20]
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

simply create a new init rn project
install plugin
linked plugin
manually verify

and run

RN Version 0.59.5
Mac OSx Mojave
Xcode 11

**Comment by farad4y** [comment]
Did you create a blank swift file ?

**Comment by imadarif** [comment]
yes

Sent from my iPhone

On 07-Oct-2019, at 8:45 PM, Faraday <notifications@github.com> wrote:

﻿

Did you create a blank swift file ?

**Comment by imadarif** [comment]
i just create two files one is html file copy paste, second is .h file

**Comment by farad4y** [comment]
I think this problem is not related with library because i got so many errors on Xcode 11
We are using Xcode 11.2 Beta. I recommend you upgrading your RN version 0.60+ and use pod installation.

**Comment by imadarif** [comment]
i can't update, is there any possibility to fix it on 0.59.5 because i am using other 0.60 plugin with same rn config by making few changes for androidx to android.

**Comment by imadarif** [comment]
is this issue because of swift file ? i have not created it in project.

**Comment by farad4y** [comment]
Could you send full error message? and can you build your project when you delete this library?

**Comment by farad4y** [comment]
No info
