### ISSUE TITLE
Can this this sdk have support for multiple video ids

### ISSUE THREAD

**Issue by bhaveshsilversky** [up-inside/react-native-youtube-sdk#21]
Hi,
Thanks for this great sdk. i would like if this sdk has feature for playing multiple video id, that could be play in sequence and also please provide an option to disable share option from the sdk.

**Comment by farad4y** [comment]
Actually we don't want to increase complexity on native side because you can do this on JS side.
I don't understand exactly what you mean with share option.

**Comment by bhaveshsilversky** [comment]
when we do the fullscreen there we have option for watch later and share can we disable it. by providing some prop to it

**Comment by farad4y** [comment]
Ok, that make sense. We can make these props dynamic actually.
