### ISSUE TITLE
UIManager WARNING  UIManager['YouTubeView'] is no longer supported.

### ISSUE THREAD

**Issue by Cyberfolks** [up-inside/react-native-youtube-sdk#22]
Accessing view manager configs directly off UIManager via UIManager['YouTubeView'] is no longer supported. Use UIManager.getViewManagerConfig('YouTubeView') instead.

**Comment by farad4y** [comment]
If u deal with, send pull request. We don’t have enough time to do that right now

**Comment by Cyberfolks** [comment]
wiat will try to make a request. im doing this 1st time.

**Comment by Cyberfolks** [comment]
please check push request. now user can remove example project that was case of errors and double gradle and other files.

**Comment by MacKentoch** [comment]
Did not have issues with a RN 0.60.5 app.
I just follow documentation and only iOS was a bit more particular
