### ISSUE TITLE
Issue: ITMS-90809: Deprecated API Usage - Deprecated UIWebView APIs

### ISSUE THREAD

**Issue by NarasimhaReddyY** [up-inside/react-native-youtube-sdk#28]
Any Update on **WkWebView** implementation?

**Comment by farad4y** [comment]
I will start to update soon. I don't have enough time to implement right now.

**Comment by NarasimhaReddyY** [comment]
@farad4y Thanks for the swift response.

**Comment by bneigher** [comment]
🙏

**Comment by farad4y** [comment]
I implemented WKWebView, could you test it ? @bneigher @NarasimhaReddyY

**Comment by bneigher** [comment]
@farad4y just gave it a swap in my app and everything seems to work 👍

**Comment by farad4y** [comment]
WkWebView implemented on 1.0.6 version

**Comment by bneigher** [comment]
🙌
