### ISSUE TITLE
Rotating not going into full screen

### ISSUE THREAD

**Issue by mattruddy** [up-inside/react-native-youtube-sdk#29]
below is my config, for some reason when switching to landscape, the player will not go into fullscreen. (I even confirmed that !isPortait() is true)

`          <YouTubePlayer
            ref={ytRef}
            videoId={id}
            autoPlay={false}
            fullscreen={!isPortrait()}
            showFullScreenButton={true}
            showSeekBar={true}
            showPlayPauseButton={true}
            startTime={5}
            style={{ width: "100%", height: 200 }}
          />`

this is awesome btw!

**Comment by farad4y** [comment]
Platform and much more info about React version etc ?

**Comment by mattruddy** [comment]
@farad4y 

react-native: 0.61.4

and its both IOS and Android for me

**Comment by ducpt2** [comment]
i met the same issue, change props fullscreen to true/false do not work.

**Comment by farad4y** [comment]
This is a native library so when state changed, fullscreen parameter won't be sent native side.
If you want to use dynamic fullscreen param, view must be re-rendered.
@mattruddy @ducpt2
