### ISSUE TITLE
iOS showFullScreenButton not display fullscreen button.

### ISSUE THREAD

**Issue by ducpt2** [up-inside/react-native-youtube-sdk#31]
iOS showFullScreenButton not display fullscreen button.

"react-native": "0.61.5",
"react-native-youtube-sdk": "^1.0.4",

Thank you for greate lib.

**Comment by bilalcorbacioglu** [comment]
Hi, I have the same issue. +1

"react-native": "0.62.1",
"react-native-youtube-sdk": "^1.0.6",

@farad4y

**Comment by MahmoudShaeer** [comment]
same here :/

**Comment by farad4y** [comment]
I have solved issue, new version will be released today
@bilalcorbacioglu @MacKentoch @ducpt2

**Comment by aaron-dsilva-opsfuse** [comment]
This button is no longer visible

**Comment by AaronDsilva97** [comment]
https://github.com/AaronDsilva97/react-native-youtube-sdk
Have forked this library and the full screen button is visible by default

There is something wrong with showFullScreenButton
