### ISSUE TITLE
Android - All videos are opened on mount if fullscreen is set to true

### ISSUE THREAD

**Issue by sulagarde** [up-inside/react-native-youtube-sdk#38]
Hi,
I encountered a problem with Android: If I have multiple youtube videos on the same page they are all entered in fullscreen on component mount if I set fullscreen to true.
Everything works perfect on iOs.

Maybe the resolution of this issue is related to the previous issue I encountered [issue-35](https://github.com/up-inside/react-native-youtube-sdk/issues/35)

Implementation:
```
<YouTubePlayer
    videoId={videoId}
    autoplay={false}
    fullscreen
    style={{ width: '100%', height: isTalk ? 150 : 200 }}
    onReady={(e) => console.log('onReady', e)}
    onError={(e) => console.log('onError', e.error)}
    onChangeState={(e) => console.log('onChangeState', e.state)}
    onChangeFullscreen={(e) => console.log('onChangeFullscreen', e.isFullscreen)}
/>
```

versions:
react-native-youtube-sdk: 1.0.9
react-native: 0.60.6

**Comment by srfaytkn** [comment]
If you set the fullscreen prop to true, the component starts a native activity when connected to the screen. You should use the showFullScreenButton prop.
