### ISSUE TITLE
Can Hidden Header Title Youtube at start video?

### ISSUE THREAD

**Issue by EkoSetiyo13** [up-inside/react-native-youtube-sdk#45]
pls help

**Comment by PitipongXYZ** [comment]
I'm waiting for the answer too.
Thank you in advance.

**Comment by farad4y** [comment]
https://developers.google.com/youtube/player_parameters?hl=en

YouTube Documention:

The showinfo parameter, which indicates whether the player should display information like the video title and uploader before the video starts playing, is also being deprecated. Following the change, the channel avatar and video title will always display before playback begins, when playback is paused, and when playback ends. The avatar being displayed is new behavior that will be consistent across all embedded players.

These changes will become effective on or after September 25, 2018. After that time, the showinfo parameter will be ignored. The behavior following the changes is consistent with the current default behavior for embedded players with the exception of the channel avatar changes mentioned above.

https://github.com/up-inside/react-native-youtube-sdk/blob/8fa70d0b7d8c34e590ce8f100cbe57b30958ddf0/ios/YouTubeView.swift#L24

You can try to change these parameters but many of them not working anymore. If you find a way to do that, you can send pull request.
